Communication.md
MIT-Emerging-Talent/ET6-foundations-group-26 pull request #3
Opened 2024-12-26 12:45 UTC by AseelOmer

This PR adds a new communication plan, including an updated schedule and task details for team collaboration.

2024-12-26 13:30 UTC, Sufi-to submitted a review, later dismissed

2024-12-26 13:32 UTC, omniaNS commented on collaboration/communication.md
> +| Eveyday   | Slack             | Quick updates on progress and blockers.                                |
Typo: 'Eveyday' should be corrected to 'Everyday'

2024-12-26 13:40 UTC, omniaNS requested changes
Correct the typo in line 7 of communication.md

2024-12-26 18:42 UTC, CaesarGhazi reviewed
Looks great, other than that typo that Omnia pointed out i don't see anything wrong with it. GREAT JOB!!!!

2024-12-26 19:07 UTC, Nada-saad635 commented
GREAT JOB!

2024-12-27 08:25 UTC, omniaNS approved these changes

2024-12-27 16:04 UTC, Nada-saad635 reviewed
seems nice

2024-12-27 16:12 UTC, merged

2024-12-27 16:14 UTC, Nada-saad635 reviewed
.

2024-12-29 15:08 UTC, heba3 commented
Good job!

2024-12-29 15:41 UTC, heba3 reviewed
Good job!