Add percentage letter function
MIT-Emerging-Talent/ET6-foundations-group-26 pull request #34
Opened 2024-12-31 14:01 UTC by heba3

## Behavior

### Files

- [ ] The file name describes the function's behavior
- [ ] There is a module docstring in the function file
- [ ] The test file's name matches the function file name -
  `/tests/test_file_name.py`
- [ ] There is a module docstring in the tests file

### Unit Tests

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Every unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
  - [ ] There is no logic in the unit test
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases

### Function Docstring

- [ ] The function's behavior is described
- The function's arguments are described:
  - [ ] Type
  - [ ] Purpose
  - [ ] Other assumptions (eg. if it's a number, what's the expected range?)
- The return value is described
  - [ ] Type
  - [ ] Other assumptions are documented
- The defensive assertions are documented using `Raises:`
  - [ ] Each assumption about an argument is checked with an assertion
  - [ ] Each assertion checks for _only one_ assumption about the argument
- [ ] Include 3 or more (passing!) doctests

### The Function

- [ ] The function's name describes it's behavior
- [ ] The function's name matches the file name
- [ ] The function has correct type annotations

## Strategy

### Do's

- [ ] Variable names help to understand the strategy
- [ ] Any comments are clear and describe the strategy
- [ ] Lines of code are spaced to help show different stages of the strategy

### Don'ts

- [ ] The function's strategy _is not_ described in the documentation
- [ ] Comments explain the _strategy_, **not** the _implementation_
- [ ] The function _does not_ have more comments than code
  - If it does, consider finding a new strategy or a simpler implementation

## Implementation

- [ ] The code passes the formatting checks
- [ ] The code passes all Ruff linting checks
- [ ] The code has no (reasonable) Pylint errors
  - In code review, you can decide when fixing a Pylint error is helpful and
    when it's too restricting.
- [ ] Variables are named with snake_case
- [ ] Variable names are clear and helpful
- [ ] The code follows the strategy as simply as possible
- [ ] The implementation is as simple as possible given the strategy
- [ ] The code includes defensive assertions
- [ ] Defensive assertions include as little logic as possible

2024-12-31 22:33 UTC, CaesarGhazi reviewed
OHMYGOOOD!!! HEBAAA, you've made my life so much easier.
i don't even know what to do.

2024-12-31 23:35 UTC, CaesarGhazi requested changes
just the variable names, other than that it's wonderful

2024-12-31 23:35 UTC, CaesarGhazi commented on solutions/percentage_letter.py
> +def percentage_letter(s: str, letter: str) -> int:
GREAT JOB!!! 👏

2024-12-31 23:35 UTC, CaesarGhazi commented on solutions/percentage_letter.py
> +def percentage_letter(s: str, letter: str) -> int:
i have only one suggestion.
which is just the variable naming.
so just the variable 's' , i'd just name it sumn else like sentence or word or text or anything you'd like really just to make the code more readable.
other than that heba, i'm pretty satisfied 😊 .

2025-01-01 09:39 UTC, heba3 commented on solutions/percentage_letter.py
> +def percentage_letter(s: str, letter: str) -> int:
@CaesarGhazi Thank you for your suggestion! I agree and will update the variable name.
I truly appreciate your feedback. Thanks again for helping improve the code!

2025-01-01 12:26 UTC, Elshikh-Amro commented
this is amaziiiiiing

2025-01-01 12:31 UTC, Elshikh-Amro commented on solutions/percentage_letter.py
> +def percentage_letter(s: str, letter: str) -> int:
i was going to mention that but goooood work everyone

2025-01-01 12:33 UTC, Elshikh-Amro commented
i think you should define the variables more clearly in order to use snake method like 'count' can be 'count_letters'

2025-01-01 12:53 UTC, heba3 commented
@Elshikh-Amro Thank you for your feedback; I appreciate your time and suggestions. Based on your input, I’ve updated the variable name to count_letters for clarity. I typically use snake_case for multi-word names and keep single-word names simpler, but I agree this change improves readability.

2025-01-01 17:05 UTC, CaesarGhazi approved these changes

2025-01-01 17:06 UTC, merged